{{if (eq .Values.DataEase.engine_mode "cluster")}}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{.Values.kettle.host}}
  labels:
    app: {{.Values.kettle.host}}
spec:
  replicas: {{.Values.kettle.replicas}}
  selector:
    matchLabels:
      app: {{.Values.kettle.host}}
  template:
    metadata:
      labels:
        app: {{.Values.kettle.host}}
    spec:
      containers:
        - name: {{.Values.kettle.host}}
          image: {{.Values.common.imagePrefix}}{{.Values.kettle.image}}:{{.Values.kettle.imageTag}}
          imagePullPolicy: {{.Values.common.imagePullPolicy}}
          resources:
            limits:
              cpu: {{.Values.kettle.resourceLimits.cpu}}
              memory: {{.Values.kettle.resourceLimits.memory}}
            requests:         
              memory: 200Mi
              cpu: 0.2
          env:
            - name: PENTAHO_DI_JAVA_OPTIONS
              value: {{.Values.kettle.java_options}}
          ports:
            - name: tcp
              containerPort: 18080
          volumeMounts:
            - name: opt-dataease-data-kettle
              mountPath: /opt/dataease/data/kettle
            - name: opt-dataease-xml-kettle
              mountPath: /opt/dataease/conf/.kettle/
              subPath: repositories.xml
            - name: opt-dataease-properties-kettle
              mountPath: /opt/dataease/conf/.kettle/
              subPath: kettle.properties
      volumes:
        - name: opt-dataease-data-kettle
          persistentVolumeClaim:
            claimName: kettle-data-pvc
        - name: opt-dataease-xml-kettle
          configMap:
            name: kettle-xml
        - name: opt-dataease-properties-kettle
          configMap:
            name: kettle-properties            
          
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.kettle.host}}
  labels:
    app: {{.Values.kettle.host}}
spec:
  clusterIP: None
  selector:
    app: {{.Values.kettle.host}}
  ports:
    - name: tcp
      port: 18080
      protocol: TCP
{{end}}
